Implement Apple Rosetta translation check
runningcode/gradle-doctor pull request #220
Opened 2022-07-20 09:30 UTC by GediminasZukas

Solves: https://github.com/runningcode/gradle-doctor/issues/209

Used `sysctl.proc_translated` API via bash in order to determine if process is running under Rosetta or not according to documentation: https://developer.apple.com/documentation/apple-silicon/about-the-rosetta-translation-environment#Determine-Whether-Your-App-Is-Running-as-a-Translated-Binary

Additional related thought: maybe we need to make this check more generic and compare machine CPU architecture with running JDK target architecture? Something similar to: https://github.com/runningcode/gradle-doctor/issues/209#issuecomment-1132645634  As hardware for Windows or Linux may benefit from ARM architecture in the future as well (maybe already there is some variants in the market).

2022-07-20 21:11 UTC, runningcode requested changes
thanks for doing this! just a comment on the commandline usage

2022-07-21 14:47 UTC, GediminasZukas commented on doctor-plugin/src/main/java/com/osacky/doctor/internal/CliCommandExecutor.kt
> +class CliCommandExecutor {
Made a change. Additionally had to bump Gradle to the newest 7.5 version in order to use new API. Thus, check won't be backwards compatible and will work only if clients will use Gradle 7.5+.

2022-07-21 14:59 UTC, GediminasZukas commented on doctor-plugin/src/main/java/com/osacky/doctor/internal/CliCommandExecutor.kt
> +class CliCommandExecutor {
Maybe better to update Gradle in a separate PR?

2022-08-08 09:05 UTC, runningcode commented on doctor-plugin/src/main/java/com/osacky/doctor/internal/CliCommandExecutor.kt
> +class CliCommandExecutor {
Ah good point. Let's see which tests pass here. There is a cross version compatibility test which might not work.

2022-08-08 09:05 UTC, runningcode commented
Thanks for the ping. Running tests now.

2022-08-09 05:09 UTC, GediminasZukas commented on doctor-plugin/src/main/java/com/osacky/doctor/internal/CliCommandExecutor.kt
> +class CliCommandExecutor {
Tests run failed due to lint errors. Fixed it with most recent commit.

2022-09-05 10:33 UTC, julioz commented on doctor-plugin/src/test/java/com/osacky/doctor/PluginIntegrationTest.kt
>              // Keep this list to 5 as testing against too many versions causes OOMs.
with the change, this comment rotted: there are now 6 versions in the returned list, going against the advice here.

2022-09-14 14:18 UTC, GediminasZukas commented on doctor-plugin/src/main/java/com/osacky/doctor/internal/CliCommandExecutor.kt
> +class CliCommandExecutor {
@runningcode, could you review again and launch tests? Seems found the cause of failing test and fixed it.

2022-09-14 14:19 UTC, GediminasZukas commented on doctor-plugin/src/test/java/com/osacky/doctor/PluginIntegrationTest.kt
>              // Keep this list to 5 as testing against too many versions causes OOMs.
Good question, actually we have 7 versions here now. @runningcode, how to proceed with this?

2023-01-05 09:28 UTC, GediminasZukas commented
@runningcode, friendly ping. How we can proceed further with this change?

2023-01-05 22:14 UTC, runningcode approved these changes
thanks for the ping, please remove those two versions to keep the list to 5 and we can proceed!

2023-01-05 22:14 UTC, runningcode commented on doctor-plugin/src/test/java/com/osacky/doctor/PluginIntegrationTest.kt
>              // Keep this list to 5 as testing against too many versions causes OOMs.
let's remove 6.1.1 and 7.3.3

2023-01-06 07:52 UTC, GediminasZukas commented
Done!

2023-01-17 09:37 UTC, GediminasZukas commented
@runningcode, can we merge this?

2023-01-17 09:38 UTC, merged